//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arhive2018.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ELMA-TEST\\SQLEXPRESS;Initial Catalog=ARHIVE1;User ID=sa;Password=!!qa" +
            "zxsw@123")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT     TOP (1)       FIO, ISADMIN, BLOCKED,[ID],[DESCRIPTION]\r\n\r\nFROM        " +
            "    dbo.[USER]\r\nWHERE        (LOGIN = @lgn) AND (PASSWORD = @psw)")]
        public string CheckUser {
            get {
                return ((string)(this["CheckUser"]));
            }
            set {
                this["CheckUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ELMA-TEST\\SQLEXPRESS;Initial Catalog=ARHIVE1;User ID=sa;Password=!!qa" +
            "zxsw@123")]
        public string ARHIVE1ConnectionString {
            get {
                return ((string)(this["ARHIVE1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" UPDATE [ARHIVE1].[dbo].[ARHIVE]\r\n   SET [OBJECT] =@obj\r\n      ,[AGREEMENT] = @ag" +
            "r\r\n      ,[RELEASE_DATE] = @date\r\n      ,[USER_ID] = @usr\r\n      ,[REPORT_ID] = " +
            "@rep\r\n      ,[QUANITY] = @qty\r\n      ,[COMMENT] = @com\r\n WHERE ID=@id")]
        public string UpdateRow {
            get {
                return ((string)(this["UpdateRow"]));
            }
            set {
                this["UpdateRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@" INSERT INTO [ARHIVE1].[dbo].[ARHIVE]
   ( [OBJECT]
      ,[AGREEMENT] 
      ,[RELEASE_DATE] 
      ,[USER_ID] 
      ,[REPORT_ID]
      ,[QUANITY] 
      ,[COMMENT] 
,[CREATED_DATE]
,[CREATED_BY]
)
OUTPUT inserted.id
 VALUES (@obj,@agr,@date,@usr,@rep,@qty,@com,@createdOn,@createdBy)")]
        public string InsertRow {
            get {
                return ((string)(this["InsertRow"]));
            }
            set {
                this["InsertRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" DELETE FROM [ARHIVE1].[dbo].[ARHIVE]\r\n  WHERE ID=@id")]
        public string DeleteRow {
            get {
                return ((string)(this["DeleteRow"]));
            }
            set {
                this["DeleteRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [REPORT] ,[ID] FROM [ARHIVE1].[dbo].[REPORT_TYPE] WHERE BLOCKED=0")]
        public string SelectReport {
            get {
                return ((string)(this["SelectReport"]));
            }
            set {
                this["SelectReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT 1 FROM [ARHIVE1].[dbo].[ARHIVE] WHERE REPORT_ID=@ID")]
        public string CheckIfReportInUse {
            get {
                return ((string)(this["CheckIfReportInUse"]));
            }
            set {
                this["CheckIfReportInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("  SELECT 1 FROM [ARHIVE1].[dbo].[ARHIVE] WHERE ID=@ID")]
        public string CheckIfUserInUse {
            get {
                return ((string)(this["CheckIfUserInUse"]));
            }
            set {
                this["CheckIfUserInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArhivePath {
            get {
                return ((string)(this["ArhivePath"]));
            }
            set {
                this["ArhivePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [PATH] FROM [ARHIVE1].[dbo].[PATH] WHERE ID=1")]
        public string GetArhivePath {
            get {
                return ((string)(this["GetArhivePath"]));
            }
            set {
                this["GetArhivePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [ARHIVE1].[dbo].[PATH] SET [PATH]=@PATH WHERE ID=1")]
        public string UpdatePath {
            get {
                return ((string)(this["UpdatePath"]));
            }
            set {
                this["UpdatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogoPath {
            get {
                return ((string)(this["LogoPath"]));
            }
            set {
                this["LogoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [PATH] FROM [ARHIVE1].[dbo].[PATH] WHERE ID=2")]
        public string GetLogoPath {
            get {
                return ((string)(this["GetLogoPath"]));
            }
            set {
                this["GetLogoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [ARHIVE1].[dbo].[PATH] SET [PATH]=@PATH WHERE ID=2")]
        public string UpdatePathLogo {
            get {
                return ((string)(this["UpdatePathLogo"]));
            }
            set {
                this["UpdatePathLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [FIO] ,[ID] FROM [ARHIVE1].[dbo].[USER] WHERE BLOCKED=0")]
        public string SelectUser {
            get {
                return ((string)(this["SelectUser"]));
            }
            set {
                this["SelectUser"] = value;
            }
        }
    }
}
